<?php

namespace Database\Seeders;

use App\Models\City;
use App\Models\Country;
use Illuminate\Database\Seeder;

class CountriesAndCitiesSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            'United States' => ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'Philadelphia', 'San Antonio', 'San Diego', 'Dallas', 'San Jose', 'Miami', 'Denver', 'Boston', 'Seattle', 'Las Vegas'],
            'United Kingdom' => ['London', 'Manchester', 'Birmingham', 'Leeds', 'Glasgow', 'Liverpool', 'Newcastle', 'Sheffield', 'Bristol', 'Edinburgh'],
            'Canada' => ['Toronto', 'Vancouver', 'Montreal', 'Calgary', 'Ottawa', 'Winnipeg', 'Quebec City', 'Edmonton', 'Victoria', 'Hamilton'],
            'Australia' => ['Sydney', 'Melbourne', 'Brisbane', 'Perth', 'Adelaide', 'Gold Coast', 'Canberra', 'Newcastle', 'Wollongong', 'Logan City'],
            'India' => ['Mumbai', 'Delhi', 'Bangalore', 'Hyderabad', 'Chennai', 'Kolkata', 'Pune', 'Ahmedabad', 'Jaipur', 'Lucknow', 'Chandigarh', 'Goa'],
            'China' => ['Beijing', 'Shanghai', 'Guangzhou', 'Shenzhen', 'Chongqing', 'Xi\'an', 'Hangzhou', 'Nanjing', 'Sichuan', 'Wuhan', 'Tianjin', 'Chengdu'],
            'Japan' => ['Tokyo', 'Osaka', 'Kyoto', 'Yokohama', 'Nagoya', 'Sapporo', 'Fukuoka', 'Kobe', 'Kawasaki', 'Saitama', 'Hiroshima', 'Osaka'],
            'France' => ['Paris', 'Marseille', 'Lyon', 'Toulouse', 'Nice', 'Nantes', 'Strasbourg', 'Montpellier', 'Bordeaux', 'Lille'],
            'Germany' => ['Berlin', 'Munich', 'Frankfurt', 'Cologne', 'Hamburg', 'Stuttgart', 'Düsseldorf', 'Dortmund', 'Essen', 'Leipzig'],
            'Italy' => ['Rome', 'Milan', 'Venice', 'Florence', 'Naples', 'Bologna', 'Turin', 'Genoa', 'Palermo', 'Verona'],
            'Spain' => ['Madrid', 'Barcelona', 'Valencia', 'Seville', 'Bilbao', 'Malaga', 'Murcia', 'Palma', 'Las Palmas', 'Alicante'],
            'United Arab Emirates' => ['Dubai', 'Abu Dhabi', 'Sharjah', 'Ajman', 'Ras al-Khaimah', 'Fujairah', 'Umm Al Quwain'],
            'Saudi Arabia' => ['Riyadh', 'Jeddah', 'Mecca', 'Medina', 'Dammam', 'Khobar', 'Abha', 'Riyadh'],
            'Thailand' => ['Bangkok', 'Chiang Mai', 'Phuket', 'Pattaya', 'Krabi', 'Koh Samui', 'Udon Thani', 'Nakhon Ratchasima'],
            'Singapore' => ['Singapore'],
            'Malaysia' => ['Kuala Lumpur', 'Penang', 'Johor Bahru', 'Kuching', 'Ipoh', 'Malacca', 'Selangor'],
            'Philippines' => ['Manila', 'Cebu', 'Davao', 'Quezon City', 'Caloocan', 'Makati', 'Pasig', 'Las Piñas'],
            'Indonesia' => ['Jakarta', 'Surabaya', 'Bandung', 'Medan', 'Semarang', 'Makassar', 'Palembang', 'Depok'],
            'Vietnam' => ['Ho Chi Minh City', 'Hanoi', 'Da Nang', 'Hai Phong', 'Can Tho', 'Bien Hoa', 'Hue'],
            'South Korea' => ['Seoul', 'Busan', 'Incheon', 'Daegu', 'Daejeon', 'Gwangju', 'Ulsan', 'Suwon'],
            'Turkey' => ['Istanbul', 'Ankara', 'Izmir', 'Bursa', 'Antalya', 'Konya', 'Gaziantep', 'Kayseri'],
            'Egypt' => ['Cairo', 'Alexandria', 'Giza', 'Sharm El-Sheikh', 'Luxor', 'Aswan', 'Port Said'],
            'South Africa' => ['Johannesburg', 'Cape Town', 'Durban', 'Pretoria', 'Bloemfontein', 'Port Elizabeth', 'Tshwane'],
            'Brazil' => ['São Paulo', 'Rio de Janeiro', 'Brasília', 'Salvador', 'Fortaleza', 'Belo Horizonte', 'Manaus', 'Curitiba'],
            'Mexico' => ['Mexico City', 'Monterrey', 'Cancún', 'Playa del Carmen', 'Guadalajara', 'Veracruz', 'Acapulco', 'Mazatlán'],
            'Argentina' => ['Buenos Aires', 'Córdoba', 'Rosario', 'Mendoza', 'La Plata', 'Mar del Plata', 'San Miguel de Tucumán'],
            'Colombia' => ['Bogotá', 'Medellín', 'Cali', 'Barranquilla', 'Cartagena', 'Bucaramanga', 'Santa Marta'],
            'Peru' => ['Lima', 'Cusco', 'Arequipa', 'Trujillo', 'Chiclayo', 'Piura', 'Iquitos'],
            'Chile' => ['Santiago', 'Valparaíso', 'Concepción', 'La Serena', 'Temuco', 'Puerto Montt', 'Antofagasta'],
            'New Zealand' => ['Auckland', 'Wellington', 'Christchurch', 'Queenstown', 'Dunedin', 'Hamilton', 'Tauranga'],
            'Greece' => ['Athens', 'Thessaloniki', 'Patras', 'Heraklion', 'Larissa', 'Rhodes', 'Santorini', 'Mykonos'],
            'Portugal' => ['Lisbon', 'Porto', 'Braga', 'Covilhã', 'Faro', 'Aveiro', 'Madeira'],
            'Netherlands' => ['Amsterdam', 'Rotterdam', 'The Hague', 'Utrecht', 'Eindhoven', 'Groningen', 'Leiden'],
            'Belgium' => ['Brussels', 'Antwerp', 'Ghent', 'Charleroi', 'Liège', 'Bruges', 'Ostend'],
            'Switzerland' => ['Zurich', 'Geneva', 'Basel', 'Bern', 'Lucerne', 'Interlaken', 'Zermatt'],
            'Austria' => ['Vienna', 'Salzburg', 'Innsbruck', 'Graz', 'Linz', 'Klagenfurt', 'Hallstatt'],
            'Czech Republic' => ['Prague', 'Brno', 'Ostrava', 'Plzen', 'Olomouc', 'Ceské Budejovice'],
            'Poland' => ['Warsaw', 'Krakow', 'Wroclaw', 'Poznan', 'Gdansk', 'Szczecin', 'Katowice'],
            'Hungary' => ['Budapest', 'Debrecen', 'Szeged', 'Miskolc', 'Pecs', 'Gyor'],
            'Romania' => ['Bucharest', 'Cluj-Napoca', 'Timisoara', 'Iasi', 'Constanta', 'Craiova'],
            'Croatia' => ['Zagreb', 'Split', 'Dubrovnik', 'Rijeka', 'Osijek', 'Zadar', 'Rovinj'],
            'Norway' => ['Oslo', 'Bergen', 'Trondheim', 'Stavanger', 'Kristiansand', 'Tromsø'],
            'Sweden' => ['Stockholm', 'Gothenburg', 'Malmö', 'Uppsala', 'Västerås', 'Örebro'],
            'Finland' => ['Helsinki', 'Espoo', 'Tampere', 'Vantaa', 'Turku', 'Oulu'],
            'Denmark' => ['Copenhagen', 'Aarhus', 'Odense', 'Aalborg', 'Randers', 'Esbjerg'],
            'Iceland' => ['Reykjavik', 'Akureyri', 'Hafnarfjörður', 'Kópavogur'],
            'Ireland' => ['Dublin', 'Cork', 'Galway', 'Waterford', 'Limerick', 'Killarney'],
            'Scotland' => ['Edinburgh', 'Glasgow', 'Aberdeen', 'Stirling', 'Inverness'],
            'Wales' => ['Cardiff', 'Swansea', 'Newport', 'Caerphilly'],
            'Russia' => ['Moscow', 'Saint Petersburg', 'Novosibirsk', 'Yekaterinburg', 'Vladivostok', 'Sochi', 'Krasnoyarsk'],
            'Ukraine' => ['Kyiv', 'Kharkiv', 'Odesa', 'Dnipro', 'Lviv', 'Zaporizhzhia'],
            'Israel' => ['Jerusalem', 'Tel Aviv', 'Haifa', 'Beersheba', 'Eilat', 'Rishon LeZion'],
            'Lebanon' => ['Beirut', 'Tripoli', 'Sidon', 'Tyre', 'Baalbek'],
            'Iran' => ['Tehran', 'Mashhad', 'Isfahan', 'Tabriz', 'Shiraz', 'Qom'],
            'Pakistan' => ['Karachi', 'Lahore', 'Islamabad', 'Rawalpindi', 'Faisalabad', 'Multan'],
            'Bangladesh' => ['Dhaka', 'Chittagong', 'Khulna', 'Rajshahi', 'Sylhet'],
            'Sri Lanka' => ['Colombo', 'Kandy', 'Galle', 'Negombo', 'Anuradhapura', 'Nuwara Eliya'],
            'Nepal' => ['Kathmandu', 'Pokhara', 'Biratnagar', 'Lalitpur'],
            'Cambodia' => ['Phnom Penh', 'Siem Reap', 'Battambang', 'Kampong Cham'],
            'Laos' => ['Vientiane', 'Luang Prabang', 'Savannakhet', 'Pakse'],
            'Myanmar' => ['Yangon', 'Mandalay', 'Naypyidaw', 'Bagan', 'Inle Lake'],
            'Hong Kong' => ['Hong Kong', 'Kowloon', 'New Territories'],
            'Taiwan' => ['Taipei', 'Kaohsiung', 'Taichung', 'Tainan', 'Keelung'],
            'Kenya' => ['Nairobi', 'Mombasa', 'Kisumu', 'Nakuru', 'Eldoret'],
            'Tanzania' => ['Dar es Salaam', 'Dodoma', 'Arusha', 'Mbeya', 'Zanzibar'],
            'Uganda' => ['Kampala', 'Gulu', 'Jinja', 'Mbarara', 'Fort Portal'],
            'Morocco' => ['Casablanca', 'Fez', 'Marrakech', 'Tangier', 'Agadir', 'Essaouira'],
            'Tunisia' => ['Tunis', 'Sfax', 'Sousse', 'Kairouan', 'Djerba'],
            'Algeria' => ['Algiers', 'Oran', 'Constantine', 'Tlemcen', 'Annaba'],
            'Ethiopia' => ['Addis Ababa', 'Dire Dawa', 'Adama', 'Awassa'],
            'Nigeria' => ['Lagos', 'Abuja', 'Kano', 'Ibadan', 'Port Harcourt'],
            'Ghana' => ['Accra', 'Kumasi', 'Sekondi-Takoradi', 'Cape Coast', 'Tema'],
            'Côte d\'Ivoire' => ['Abidjan', 'Yamoussoukro', 'Bouaké', 'Daloa'],
            'Senegal' => ['Dakar', 'Saint-Louis', 'Kaolack', 'Tambacounda'],
            'Mali' => ['Bamako', 'Segou', 'Mopti', 'Gao'],
            'Burkina Faso' => ['Ouagadougou', 'Bobo-Dioulasso', 'Koudougou'],
            'Guinea' => ['Conakry', 'Kindia', 'Mamou', 'Guéckédou'],
            'Zimbabwe' => ['Harare', 'Bulawayo', 'Chitungwiza', 'Mutare'],
            'Botswana' => ['Gaborone', 'Francistown', 'Maun', 'Selibe-Phikwe'],
            'Namibia' => ['Windhoek', 'Walvis Bay', 'Swakopmund', 'Oshakati'],
            'Mozambique' => ['Maputo', 'Beira', 'Nampula', 'Chimoio'],
            'Madagascar' => ['Antananarivo', 'Antsirabe', 'Toliara', 'Fianarantsoa'],
            'Mauritius' => ['Port Louis', 'Curepipe', 'Vacoas-Phoenix', 'Beau Bassin-Rose Hill'],
            'Jamaica' => ['Kingston', 'Montego Bay', 'Spanish Town', 'Mandeville'],
            'Trinidad and Tobago' => ['Port of Spain', 'San Fernando', 'Arima', 'Point Fortin'],
            'Bahamas' => ['Nassau', 'Freeport', 'Marsh Harbour', 'George Town'],
            'Cuba' => ['Havana', 'Santiago de Cuba', 'Camagüey', 'Holguín', 'Santa Clara'],
            'Dominican Republic' => ['Santo Domingo', 'Santiago', 'La Romana', 'Puerto Plata', 'Punta Cana'],
            'Puerto Rico' => ['San Juan', 'Bayamón', 'Carolina', 'Ponce'],
            'Costa Rica' => ['San José', 'Limón', 'Alajuela', 'Cartago', 'Heredia'],
            'Panama' => ['Panama City', 'Colón', 'David', 'Penonomé'],
            'Venezuela' => ['Caracas', 'Maracaibo', 'Valencia', 'Barquisimeto', 'Ciudad Guayana'],
            'Ecuador' => ['Quito', 'Guayaquil', 'Cuenca', 'Ambato', 'Galápagos'],
            'Bolivia' => ['La Paz', 'Santa Cruz', 'Cochabamba', 'Sucre', 'Oruro'],
            'Zambia' => ['Lusaka', 'Kitwe', 'Ndola', 'Chingola'],
            'Malawi' => ['Lilongwe', 'Blantyre', 'Mzuzu', 'Zomba'],
            'Rwanda' => ['Kigali', 'Butare', 'Gitarama', 'Ruhengeri'],
            'Burundi' => ['Bujumbura', 'Gitega', 'Ngozi'],
            'Angola' => ['Luanda', 'Huambo', 'Benguela', 'Lobito'],
            'Democratic Republic of Congo' => ['Kinshasa', 'Lubumbashi', 'Mbuji-Mayi', 'Kisangani'],
            'Congo' => ['Brazzaville', 'Pointe-Noire', 'Dolisie'],
            'Cameroon' => ['Yaoundé', 'Douala', 'Garoua', 'Bamenda'],
            'Central African Republic' => ['Bangui', 'Bimbo', 'Berbérati'],
            'Gabon' => ['Libreville', 'Port-Gentil', 'Franceville'],
            'Equatorial Guinea' => ['Malabo', 'Bata', 'Ebebiyin'],
            'Belarus' => ['Minsk', 'Brest', 'Grodno', 'Vitebsk'],
            'Kazakhstan' => ['Astana', 'Almaty', 'Karaganda', 'Aktobe'],
            'Uzbekistan' => ['Tashkent', 'Samarkand', 'Bukhara', 'Andijan'],
            'Turkmenistan' => ['Ashgabat', 'Turkmenbashi', 'Türkmenabat'],
            'Tajikistan' => ['Dushanbe', 'Khujand', 'Khorog'],
            'Kyrgyzstan' => ['Bishkek', 'Osh', 'Jalal-Abad'],
            'Afghanistan' => ['Kabul', 'Kandahar', 'Herat', 'Mazar-i-Sharif'],
            'Georgia' => ['Tbilisi', 'Batumi', 'Kutaisi', 'Gori'],
            'Armenia' => ['Yerevan', 'Gyumri', 'Vanadzor'],
            'Azerbaijan' => ['Baku', 'Ganja', 'Sumgait', 'Quba'],
            'Montenegro' => ['Podgorica', 'Kotor', 'Budva', 'Bar'],
            'Bosnia and Herzegovina' => ['Sarajevo', 'Banja Luka', 'Mostar', 'Zenica'],
            'Serbia' => ['Belgrade', 'Novi Sad', 'Niš', 'Kragujevac'],
            'North Macedonia' => ['Skopje', 'Bitola', 'Kumanovo'],
            'Albania' => ['Tirana', 'Durrës', 'Vlorë', 'Shkodër'],
            'Slovenia' => ['Ljubljana', 'Maribor', 'Celje', 'Kranj'],
            'Slovakia' => ['Bratislava', 'Košice', 'Prešov', 'Žilina'],
            'Lithuania' => ['Vilnius', 'Kaunas', 'Klaipėda', 'Šiauliai'],
            'Latvia' => ['Riga', 'Daugavpils', 'Liepāja', 'Jelgava'],
            'Estonia' => ['Tallinn', 'Tartu', 'Narva', 'Pärnu'],
            'Luxembourg' => ['Luxembourg City', 'Esch-sur-Alzette', 'Differdange'],
            'Montenegro' => ['Podgorica', 'Kotor', 'Budva'],
            'Malta' => ['Valletta', 'Sliema', 'Mosta', 'Naxxar'],
            'Cyprus' => ['Nicosia', 'Limassol', 'Larnaca', 'Paphos'],
        ];

        foreach ($data as $countryName => $cities) {
            // Create or get country
            $country = Country::firstOrCreate(
                ['normalized_name' => mb_strtolower($countryName)],
                ['name' => $countryName]
            );

            // Create cities for this country
            foreach ($cities as $cityName) {
                City::firstOrCreate(
                    ['country_id' => $country->id, 'normalized_name' => mb_strtolower($cityName)],
                    ['name' => $cityName, 'country_id' => $country->id]
                );
            }
        }
    }
}
